// packages/locoui-react/src/separator/separator.tsx
"use client"

import * as React from "react"
import * as SeparatorPrimitive from "@radix-ui/react-separator"

import { cn } from "../utils/cn.ts"

const Separator = React.forwardRef<
  React.ElementRef<typeof SeparatorPrimitive.Root>,
  React.ComponentPropsWithoutRef<typeof SeparatorPrimitive.Root>
>(
  (
    { className = "", orientation = "horizontal", decorative = true, ...props },
    ref
  ) => (
    <SeparatorPrimitive.Root
      ref={ref}
      decorative={decorative}
      orientation={orientation}
      className={cn(
        "shrink-0 bg-border",
        orientation === "horizontal" ? "h-[1px] w-full" : "h-full w-[1px]",
        className
      )}
      {...props}
    />
  )
)
Separator.displayName = SeparatorPrimitive.Root.displayName

export { Separator }

// packages/locoui-vue/src/separator/separator.vue
<template>
  <separator-root
    :decorative="decorative"
    :orientation="orientation"
    :class="separatorClass"
    v-bind="$attrs"
  />
</template>

<script setup>
import { ref, computed } from "vue";
import * as SeparatorPrimitive from "@radix-ui/vue-separator";

const props = defineProps({
  className: {
    type: String,
    default: "",
  },
  orientation: {
    type: String,
    default: "horizontal",
  },
  decorative: {
    type: Boolean,
    default: true,
  },
});

const separatorClass = computed(() => [
  "shrink-0 bg-border",
  props.orientation === "horizontal" ? "h-[1px] w-full" : "h-full w-[1px]",
  props.className,
]);
</script>

<script>
export default {
  name: "Separator",
};
</script>
